/**
 * Auto-generates version info for FlashPostgre.
 * Format: 1.YYYYMMDD.buildCount
 * - YYYYMMDD: Today's date
 * - buildCount: Increments each build (persisted in .build-count file)
 */

import * as fs from 'fs';
import * as path from 'path';

const BUILD_COUNT_FILE = path.join(__dirname, '..', '.build-count');
const VERSION_FILE = path.join(__dirname, '..', 'src', 'version.ts');

function pad(n: number): string {
  return n.toString().padStart(2, '0');
}

function getBuildCount(): number {
  try {
    if (fs.existsSync(BUILD_COUNT_FILE)) {
      const count = parseInt(fs.readFileSync(BUILD_COUNT_FILE, 'utf-8').trim(), 10);
      return isNaN(count) ? 0 : count;
    }
  } catch {
    // ignore
  }
  return 0;
}

function saveBuildCount(count: number): void {
  fs.writeFileSync(BUILD_COUNT_FILE, count.toString(), 'utf-8');
}

function main(): void {
  const now = new Date();
  const year = now.getFullYear();
  const month = pad(now.getMonth() + 1);
  const day = pad(now.getDate());

  let buildCount = getBuildCount();
  buildCount++;
  saveBuildCount(buildCount);

  const version = `1.${year}${month}${day}.${buildCount}`;
  const dateStr = `${year}-${month}-${day}`;

  const content = `// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY
export const APP_VERSION = '${version}';
export const BUILD_DATE = '${dateStr}';
export const BUILD_COUNT = ${buildCount};
`;

  fs.writeFileSync(VERSION_FILE, content, 'utf-8');
  console.log(`Version generated: ${version}`);
}

main();